# Generated by Django 4.0.5 on 2022-06-23 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_review', '0003_alter_review_rating_alter_ticket_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.PositiveSmallIntegerField(choices=[(5, 'Excellent'), (4, 'Verry Good'), (3, 'Good'), (2, 'Average'), (1, 'Bad'), (0, 'Awful')]),
        ),
    ]
